### ISSUE TITLE
Assault rifle hit detection issues

### ISSUE THREAD

**Issue by Arlochorim** [GnomeModder/EnforcerMod#9]
I've noticed on a few runs now that the assault rifle has a tendency to misfire or point at the ground when aiming at targets close to the character.

I'm unsure if this is a clipping issue but for whatever reason I've noticed a lot of shots going directly into the ground when aiming straight ahead, this seems to only happen with the assault rifle skill and seems to be far more common when holding the shield up.

**Comment by crouton111** [comment]
A friend of mine and I were playing today both with the enforcer with assault rifle and we both experienced this same thing. Although we didn't notice that it was only against close enemies. It seemed to be the case with most enemies. Put another way, it felt like the bullets were firing from ground level rather than chest level so that it would catch on the slightest bit of intervening terrain even though the path to the crosshairs was clear from the player's view.

**Comment by TheTimeSweeper** [comment]
thanks for playin c:
looking at it. this will be fixed in the next update, whenever that is

**Comment by TheTimeSweeper** [comment]
fixed that shit kniggaaaaaa
